#pragma once

enum PacketID : unsigned short
{
	S2C_VALIDATION_REQUEST = 0,
	C2S_VALIDATION_RESPONSE,
	S2C_SESSION_EXPIRED_NOTIFICATION,


	C2S_LOGIN_REQUEST,
	S2C_LOGIN_RESPONSE,

	C2S_LOGOUT_REQUEST,
	S2C_LOGOUT_RESPONSE,

	C2S_JOIN_REQUEST,
	S2C_JOIN_RESPONSE,


	C2S_CREATE_ROOM_REQUEST,
	S2C_CREATE_ROOM_RESPONSE,

	C2S_JOIN_ROOM_REQUEST,
	S2C_JOIN_ROOM_RESPONSE,

	C2S_QUIT_ROOM_REQUEST,
	S2C_QUIT_ROOM_RESPONSE,

	C2S_INVITE_USER_REQUEST,
	S2C_INVITE_USER_RESPONSE,
	S2C_INVITE_USER_NOTIFICATION,


	C2S_START_GAME_REQUEST,
	S2C_START_GAME_RESPONSE,
};