#pragma once

enum PacketID : unsigned short
{
	S2C_VALIDATION_REQUEST = 0,
	C2S_VALIDATION_RESPONSE,
	S2C_SESSION_EXPIRED_NOTIFICATION,


	/// Authentication
	C2S_LOGIN_REQUEST,
	S2C_LOGIN_RESPONSE,

	C2S_LOGOUT_REQUEST,
	S2C_LOGOUT_RESPONSE,

	C2S_JOIN_REQUEST,
	S2C_JOIN_RESPONSE,


	C2S_FIND_FRIEND_REQUEST,
	S2C_FIND_FRIEND_RESPONSE,

	C2S_ADD_FRIEND_REQUEST,
	S2C_ADD_FRIEND_RESPONSE,
	S2O_ADD_FRIEND_NOTIFICATION,

	C2S_CANCEL_ADD_FRIEND_REQUEST,
	S2C_CANCEL_ADD_FRIEND_RESPONSE,
	S2O_CANCEL_ADD_FRIEND_NOTIFICATION,
	
	C2S_ACCEPT_FRIEND_REQUEST,
	S2C_ACCEPT_FRIEND_RESPONSE,
	S2O_ACCEPT_FRIEND_NOTIFICATION,

	C2S_REFUSE_FRIEND_REQUEST,
	S2C_REFUSE_FRIEND_RESPONSE,

	C2S_DEL_FRIEND_REQUEST,
	S2C_DEL_FRIEND_RESPONSE,
	S2O_DEL_FRIEND_NOTIFICATION,

	S2O_UPDATE_STATE_NOTIFICATION,


	/// GameRoom
	C2S_CREATE_ROOM_REQUEST,
	S2C_CREATE_ROOM_RESPONSE,

	C2S_JOIN_ROOM_REQUEST,
	S2C_JOIN_ROOM_RESPONSE,

	C2S_QUIT_ROOM_REQUEST,
	S2C_QUIT_ROOM_RESPONSE,

	C2S_INVITE_FRIEND_REQUEST,
	S2C_INVITE_FRIEND_RESPONSE,
	S2O_INVITE_FRIEND_NOTIFICATION,

	C2S_ACCEPT_INVITATION_REQUEST,
	S2C_ACCEPT_INVITATION_RESPONSE,

	C2S_START_GAME_REQUEST,
	S2C_START_GAME_RESPONSE,

	C2S_END_GAME_REQUEST,
	S2C_END_GAME_RESPONSE,
};

enum EUserState
{
	OFFLINE,
	IN_GAME,
	ONLINE,
	END_USER_STATE
};

enum ELoginResponse
{
	LOGIN_SUCCESS,

	WRONG_ID,
	WRONG_PW,
	ALREADY_LOGIN,
	SERVER_FAILED
};

enum ERequestState
{
	NON,
	ALREADY_REQUEST,
	ALREADY_FRIEND,
	END_REQUEST_STATE
};

enum EJoinRoomResponse
{
	SUCCESS,

	OVER_PLAYER,
	INVALID_ROOM,
	UNKNOWN
};
